version: '3.8'
services:
  db:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    
